name: "Pace main unit tests"
on:
  workflow_call:
    inputs:
      component_trigger:
        type: boolean
        default: false
        required: false
      component_repository:
        type: string
        default: 'None'
        required: false
      component_branch:
        type: string
        default: 'None'
        required: false
      component_location:
        type: string
        default: 'None'
        required: false
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]


# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:
        - name: Checkout pace if component triggered
          if:  ${{ inputs.component_trigger }}
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            repository: NOAA-GFDL/pace
            path: ${GITHUB_WORKSPACE}/pace

        - name: Checkout out component
          if:  ${{ inputs.component_trigger }}
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            repository: ${{inputs.component_repository}}
            ref: ${{inputs.component_branch}}
            path: ${GITHUB_WORKSPACE}/pace/${{inputs.component_location}}

        - name: Checkout pace if internally triggered
          if: ${{ ! inputs.component_trigger }}
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            path: ${GITHUB_WORKSPACE}/pace

        - name: install packages
          run: |
            cd ${GITHUB_WORKSPACE}/pace
            pip3 install --upgrade pip setuptools wheel
            pip3 install -r requirements_dev.txt -c constraints.txt

        - name: make input files
          run: |
            ls -R ${GITHUB_WORKSPACE}
            cd ${GITHUB_WORKSPACE}/pace
            python3 examples/generate_eta_files.py
            mkdir tests/main/input && mv eta*.nc tests/main/input/.

        - name: run tests
          run: |
            cd ${GITHUB_WORKSPACE}/pace
            pytest -x tests/main
