name: "Pace main unit tests"
on:
  workflow_call:
    inputs:
      component_trigger:
        type: boolean
        default: false
        required: false
      component_repository:
        type: string
        default: 'None'
        required: false
      component_branch:
        type: string
        default: 'None'
        required: false
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]


# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:
      - name:  Checkout pace if internally triggered
        if:  ${{ ! inputs.component_trigger}}
        run: echo "HEREHEREHERE"

      - name:  Checkout pace if internally triggered
        if:  ${{inputs.component_trigger}}
        run: echo "NOPENOPENPENOPE"

